### PR TITLE
Added support for XLIFF files

### PR DESCRIPTION
**Pull request by fabienwarniez**

### CODE REVIEW

**Comment by fabienwarniez** [comment]
@umpirsky

**Comment by umpirsky** [comment]
Thanks @fabienwarniez! :+1:

**Comment by fabienwarniez** [comment]
@umpirsky Would you mind cutting a new release that includes this PR?

**Comment by umpirsky** [comment]
@fabienwarniez Sure, done. :+1:

**Comment by fabienwarniez** [comment]
Thank you :)

**Pull request merged**
