### PR TITLE
Finishing PHP country helper

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @umpirsky 

I've finished the staled PR #99 by adding the requested exception for the file loader. Let me know if you need anything else.

Cheers,
Peter

### CODE REVIEW

**Comment by umpirsky** [comment]
Hi, thanks for your contribution, but let's stop for a moment.

Why would anyone use this instead of using intl directly like [this](https://github.com/umpirsky/country-list/blob/master/bin/build#L11-L19)?

**Comment by spekulatius** [comment]
Hey @umpirsky 

is this the intended way of usage?

Cheers,
Peter

**Comment by umpirsky** [comment]
If you want to write PHP code this package is probably not for you, you should use intl directly.

**Comment by spekulatius** [comment]
Yeah, I intend to use it with PHP and seen the helper. Should we close this then?

**Comment by umpirsky** [comment]
Yes, let's close. Thanks.

**Comment by spekulatius** [comment]
Okay, cool.

**Pull request closed without merging**
