### PR TITLE
Translated 'Côte d’Ivoire' to spanish

### PR DESCRIPTION
**Pull request by vaites**
*Côte d’Ivoire* is known in spanish as *Costa de Marfil* ([Wikipedia](https://es.wikipedia.org/wiki/Costa_de_Marfil)). I changed it in all spanish variations.

### CODE REVIEW

**Comment by umpirsky** [comment]
The data is coming form ICU database, we don't change it by hand. If you want to change it, please refer to ICU.

**Comment by vaites** [comment]
Sorry @umpirsky, didn't know that. Can you please tell me from where the data is taken?. Don't find it on readme or code...

**Comment by umpirsky** [comment]
http://site.icu-project.org/

**Comment by vaites** [comment]
Thanks, will make the changes on ICU project.

**Pull request closed without merging**
