### PR TITLE
PHP 8.0 compatibility

### LINKED ISSUE #110: Allow using with PHP > 8.0
Hi,
As for now if I'm trying to use  umpirsky/country-list on my php8 server I get this error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires umpirsky/country-list ^2.0.5 -> satisfiable by umpirsky/country-list[2.0.5].
    - umpirsky/country-list 2.0.5 requires php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
```

In my opinion, the package supports php8 without any update. we just need to allow it on the composer fie.

### PR DESCRIPTION
**Pull request by blankse**
Fix #110

### CODE REVIEW

**Comment by umpirsky** [comment]
Thanks!

**Comment by blankse** [comment]
@umpirsky Can you make a release with this change?

**Comment by umpirsky** [comment]
https://github.com/umpirsky/country-list/releases/tag/2.0.6

**Comment by blankse** [comment]
Thanks!

**Comment by blankse** [comment]
@umpirsky Can you update also Packagist? Here is only 2.0.5 https://packagist.org/packages/umpirsky/country-list

**Comment by umpirsky** [comment]
Done.

**Pull request merged**
